In [1]:
using CMPSExcitations

In [2]:
Hsingle_ll(c, μ) = ∫(∂ψ̂' * ∂ψ̂ - μ * ψ̂' * ψ̂ + c * (ψ̂')^2 * ψ̂^2, (-Inf, +Inf));
Hsingle(c, μ) = ∫(2 * ∂ψ̂' * ∂ψ̂ - 2 * μ * ψ̂' * ψ̂ + 4 * c * (ψ̂')^2 * ψ̂^2, (-Inf, +Inf));
Hcoupled(c, μ) = ∫(
    (∂ψ̂₁' * ∂ψ̂₁ - μ * ψ̂₁' * ψ̂₁ + c * (ψ̂₁')^2 * ψ̂₁^2 +
     ∂ψ̂₂' * ∂ψ̂₂ - μ * ψ̂₂' * ψ̂₂ + c * (ψ̂₂')^2 * ψ̂₂^2 +
     2 * c * (ψ̂₁') * (ψ̂₂') * ψ̂₂ * ψ̂₁), (-Inf, +Inf));

In [75]:
# canonical basis
function excitation_matrix(Heff, D)
    dim = 2 * D^2
    M = zeros(ComplexF64, dim, dim)

    for j in 1:dim
        e = zeros(ComplexF64, dim)
        e[j] = 1.0
        W1 = reshape(view(e, 1:D^2), D, D)
        W2 = reshape(view(e, D^2+1:dim), D, D)
        W1p, W2p = Heff((Constant(W1), Constant(W2)))
        M[:, j] = vcat(vec(W1p[]), vec(W2p[]))
    end

    return M
end

excitation_matrix (generic function with 1 method)

In [ ]:
c, μ = 10., 5.
tol = 1e-10

Ds = [4, 8]
D = maximum(Ds)

Niter = 10
states = Vector{InfiniteCMPS}(undef, Niter)
energies = zeros(ComplexF64, Niter)
HLL = Hsingle_ll(c, μ)

Threads.@threads for n in 1:Niter
    # HLL = Hsingle(c, μ)
    # @time stateLL = find_groundstate(Ds, HLL, YangGaudinCMPS, optalg=LBFGS(80; verbosity=1, maxiter=7000, gradtol=tol), gradtol=tol)
    # println("Energy density: ", expval(HLL.h, stateLL)[], "\n Particle density: ", expval(ψ̂' * ψ̂, stateLL)[], "\n Order parameter: ", expval(ψ̂, stateLL)[])
    # stateCLL = InfiniteCMPS(stateLL.Q, (stateLL.Rs[1], stateLL.Rs[1]))

    @time stateLL = find_groundstate(Ds, HLL, InfiniteCMPS, optalg=LBFGS(80; verbosity=1, maxiter=7000, gradtol=tol), gradtol=tol)

    states[n] = stateLL
    energies[n] = expval(HLL.h, stateLL)[]
end

Optimizing D=4
Optimizing D=4
Optimizing D=4
Optimizing D=4
Optimizing D=4
Optimizing D=4
Optimizing D=4
Optimizing D=4
Optimizing D=4
Optimizing D=4


┌ Warning: The function `scalartype` is not implemented for (values of) type `Constant{Matrix{Float64}}`;
│ this fallback will disappear in future versions of VectorInterface.jl
└ @ VectorInterface /home/ashankar/.julia/packages/VectorInterface/J6qCR/src/fallbacks.jl:20
┌ Warning: The function `scale` is not implemented for (values of) type `Tuple{Constant{Matrix{Float64}}, Float64}`;
│ this fallback will disappear in future versions of VectorInterface.jl
└ @ VectorInterface /home/ashankar/.julia/packages/VectorInterface/J6qCR/src/fallbacks.jl:67
┌ Warning: The function `add!!` is not implemented for (values of) type `Tuple{Constant{Matrix{Float64}}, Constant{Matrix{Float64}}, Float64, VectorInterface.One}`;
│ this fallback will disappear in future versions of VectorInterface.jl
└ @ VectorInterface /home/ashankar/.julia/packages/VectorInterface/J6qCR/src/fallbacks.jl:163
┌ Warning: The function `scale!!` is not implemented for (values of) type `Tuple{Constant{Matrix{Float64}}, Float64}

D = 4 | InfiniteCMPS{Constant{Matrix{Float64}}, 1}


┌ Info: LBFGS: converged after 65 iterations: f = -2.555100535381, ‖∇f‖ = 2.8094e-11
└ @ OptimKit /home/ashankar/.julia/packages/OptimKit/xpmbV/src/lbfgs.jl:138
┌ Info: UniformCMPS ground state: converged after 66 iterations: e = -2.555100535381, ‖∇e‖ = 2.8094e-11
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:127


 14.708226 seconds (59.75 M allocations: 2.967 GiB, 2.90% gc time, 634169 lock conflicts, 949.89% compilation time: <1% of which was recompilation)
---------------
Optimizing D=8
D = 4 | InfiniteCMPS{Constant{Matrix{Float64}}, 1}
 14.991065 seconds (62.26 M allocations: 3.085 GiB, 2.91% gc time, 827991 lock conflicts, 932.95% compilation time: <1% of which was recompilation)
---------------
Optimizing D=8


┌ Info: LBFGS: converged after 115 iterations: f = -2.734747817523, ‖∇f‖ = 8.9463e-11
└ @ OptimKit /home/ashankar/.julia/packages/OptimKit/xpmbV/src/lbfgs.jl:138
┌ Info: UniformCMPS ground state: converged after 116 iterations: e = -2.734747817523, ‖∇e‖ = 8.9463e-11
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:127


D = 4 | InfiniteCMPS{Constant{Matrix{Float64}}, 1}
 15.125223 seconds (62.79 M allocations: 3.108 GiB, 2.88% gc time, 964456 lock conflicts, 924.67% compilation time: <1% of which was recompilation)
---------------
Optimizing D=8
D = 4 | InfiniteCMPS{Constant{Matrix{Float64}}, 1}
 15.189853 seconds (63.07 M allocations: 3.119 GiB, 2.87% gc time, 1028758 lock conflicts, 920.74% compilation time: <1% of which was recompilation)
---------------
Optimizing D=8
D = 4 | InfiniteCMPS{Constant{Matrix{Float64}}, 1}
 15.191911 seconds (63.08 M allocations: 3.120 GiB, 2.87% gc time, 1030517 lock conflicts, 920.61% compilation time: <1% of which was recompilation)
---------------
Optimizing D=8


┌ Info: LBFGS: converged after 88 iterations: f = -2.555100535381, ‖∇f‖ = 1.5355e-11
└ @ OptimKit /home/ashankar/.julia/packages/OptimKit/xpmbV/src/lbfgs.jl:138
┌ Info: UniformCMPS ground state: converged after 89 iterations: e = -2.555100535381, ‖∇e‖ = 1.5355e-11
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:127
┌ Info: LBFGS: converged after 119 iterations: f = -2.734747817523, ‖∇f‖ = 1.7008e-11
└ @ OptimKit /home/ashankar/.julia/packages/OptimKit/xpmbV/src/lbfgs.jl:138
┌ Info: UniformCMPS ground state: converged after 120 iterations: e = -2.734747817523, ‖∇e‖ = 1.7008e-11
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:127
┌ Info: LBFGS: converged after 172 iterations: f = -2.734747817523, ‖∇f‖ = 7.3046e-11
└ @ OptimKit /home/ashankar/.julia/packages/OptimKit/xpmbV/src/lbfgs.jl:138
┌ Info: UniformCMPS ground state: converged after 173 iterations: e = -2.7347478

D = 4 | InfiniteCMPS{Constant{Matrix{Float64}}, 1}
 15.299618 seconds (64.23 M allocations: 3.171 GiB, 2.91% gc time, 1105456 lock conflicts, 917.72% compilation time: <1% of which was recompilation)
---------------
Optimizing D=8


┌ Info: LBFGS: converged after 149 iterations: f = -2.734747817523, ‖∇f‖ = 7.1304e-12
└ @ OptimKit /home/ashankar/.julia/packages/OptimKit/xpmbV/src/lbfgs.jl:138
┌ Info: UniformCMPS ground state: converged after 150 iterations: e = -2.734747817523, ‖∇e‖ = 7.1304e-12
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:127


D = 4 | InfiniteCMPS{Constant{Matrix{Float64}}, 1}
 15.356811 seconds (65.01 M allocations: 3.207 GiB, 2.95% gc time, 1132977 lock conflicts, 915.23% compilation time: <1% of which was recompilation)
---------------
Optimizing D=8


┌ Info: LBFGS: converged after 129 iterations: f = -2.734747817523, ‖∇f‖ = 8.5502e-11
└ @ OptimKit /home/ashankar/.julia/packages/OptimKit/xpmbV/src/lbfgs.jl:138
┌ Info: UniformCMPS ground state: converged after 130 iterations: e = -2.734747817523, ‖∇e‖ = 8.5502e-11
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:127
┌ Info: UniformCMPS ground state: initialization with e = -2.734747817693
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:115


D = 4 | InfiniteCMPS{Constant{Matrix{Float64}}, 1}
 15.742850 seconds (66.57 M allocations: 3.295 GiB, 2.92% gc time, 1523654 lock conflicts, 909.79% compilation time: <1% of which was recompilation)
---------------
Optimizing D=8


┌ Info: LBFGS: converged after 182 iterations: f = -2.734747817523, ‖∇f‖ = 2.0281e-11
└ @ OptimKit /home/ashankar/.julia/packages/OptimKit/xpmbV/src/lbfgs.jl:138
┌ Info: UniformCMPS ground state: converged after 183 iterations: e = -2.734747817523, ‖∇e‖ = 2.0281e-11
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:127
┌ Info: UniformCMPS ground state: initialization with e = -2.734747817707
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:115
┌ Info: UniformCMPS ground state: initialization with e = -2.734747817497
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:115
┌ Info: UniformCMPS ground state: initialization with e = -2.734747817479
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:115
┌ Info: UniformCMPS ground state: initialization with e = -

D = 4 | InfiniteCMPS{Constant{Matrix{Float64}}, 1}
 17.191434 seconds (67.65 M allocations: 3.380 GiB, 2.73% gc time, 3053678 lock conflicts, 828.89% compilation time: <1% of which was recompilation)
---------------
Optimizing D=8


┌ Info: LBFGS: converged after 198 iterations: f = -2.734747817523, ‖∇f‖ = 3.2500e-11
└ @ OptimKit /home/ashankar/.julia/packages/OptimKit/xpmbV/src/lbfgs.jl:138
┌ Info: UniformCMPS ground state: converged after 199 iterations: e = -2.734747817523, ‖∇e‖ = 3.2500e-11
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:127
┌ Info: UniformCMPS ground state: initialization with e = -2.734747817582
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:115


D = 4 | InfiniteCMPS{Constant{Matrix{Float64}}, 1}
 18.626762 seconds (68.55 M allocations: 3.458 GiB, 2.56% gc time, 4576786 lock conflicts, 765.02% compilation time: <1% of which was recompilation)
---------------
Optimizing D=8


┌ Info: LBFGS: converged after 280 iterations: f = -2.734747817523, ‖∇f‖ = 3.5545e-11
└ @ OptimKit /home/ashankar/.julia/packages/OptimKit/xpmbV/src/lbfgs.jl:138
┌ Info: UniformCMPS ground state: converged after 281 iterations: e = -2.734747817523, ‖∇e‖ = 3.5545e-11
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:127
┌ Info: UniformCMPS ground state: initialization with e = -2.734747817533
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:115


D = 8 | InfiniteCMPS{Constant{Matrix{Float64}}, 1}
 33.816690 seconds (20.32 M allocations: 1.661 GiB, 0.45% gc time, 32153342 lock conflicts, 7.81% compilation time)
---------------
 49.795522 seconds (87.68 M allocations: 5.002 GiB, 1.24% gc time, 33117964 lock conflicts, 296.51% compilation time: <1% of which was recompilation)


┌ Info: LBFGS: converged after 189 iterations: f = -2.734747817523, ‖∇f‖ = 5.0342e-11
└ @ OptimKit /home/ashankar/.julia/packages/OptimKit/xpmbV/src/lbfgs.jl:138
┌ Info: UniformCMPS ground state: converged after 190 iterations: e = -2.734747817523, ‖∇e‖ = 5.0342e-11
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:127


D = 8 | InfiniteCMPS{Constant{Matrix{Float64}}, 1}
 40.021395 seconds (26.25 M allocations: 2.043 GiB, 0.47% gc time, 37249516 lock conflicts, 7.47% compilation time)
---------------
 54.768917 seconds (86.13 M allocations: 5.016 GiB, 1.12% gc time, 37891878 lock conflicts, 266.92% compilation time: <1% of which was recompilation)


┌ Info: LBFGS: converged after 201 iterations: f = -2.734747817523, ‖∇f‖ = 4.3335e-11
└ @ OptimKit /home/ashankar/.julia/packages/OptimKit/xpmbV/src/lbfgs.jl:138
┌ Info: UniformCMPS ground state: converged after 202 iterations: e = -2.734747817523, ‖∇e‖ = 4.3335e-11
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:127


D = 8 | InfiniteCMPS{Constant{Matrix{Float64}}, 1}
 58.136556 seconds (32.15 M allocations: 2.719 GiB, 0.41% gc time, 53418690 lock conflicts, 4.92% compilation time)
---------------
 74.182159 seconds (99.81 M allocations: 6.071 GiB, 0.95% gc time, 54449331 lock conflicts, 199.33% compilation time: <1% of which was recompilation)


┌ Info: LBFGS: converged after 330 iterations: f = -2.761265509087, ‖∇f‖ = 5.9514e-11
└ @ OptimKit /home/ashankar/.julia/packages/OptimKit/xpmbV/src/lbfgs.jl:138
┌ Info: UniformCMPS ground state: converged after 331 iterations: e = -2.761265509087, ‖∇e‖ = 5.9514e-11
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:127


D = 8 | InfiniteCMPS{Constant{Matrix{Float64}}, 1}
 58.036679 seconds (31.00 M allocations: 2.668 GiB, 0.39% gc time, 53351048 lock conflicts, 3.98% compilation time)
---------------
 73.350665 seconds (95.25 M allocations: 5.841 GiB, 0.92% gc time, 54456584 lock conflicts, 199.30% compilation time: <1% of which was recompilation)


┌ Info: LBFGS: converged after 335 iterations: f = -2.761265509087, ‖∇f‖ = 2.5276e-11
└ @ OptimKit /home/ashankar/.julia/packages/OptimKit/xpmbV/src/lbfgs.jl:138
┌ Info: UniformCMPS ground state: converged after 336 iterations: e = -2.761265509087, ‖∇e‖ = 2.5276e-11
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:127


D = 8 | InfiniteCMPS{Constant{Matrix{Float64}}, 1}
 61.283061 seconds (32.10 M allocations: 2.793 GiB, 0.38% gc time, 55872243 lock conflicts, 3.54% compilation time)
---------------
 77.487757 seconds (101.68 M allocations: 6.233 GiB, 0.93% gc time, 57005283 lock conflicts, 190.81% compilation time: <1% of which was recompilation)


┌ Info: LBFGS: converged after 328 iterations: f = -2.761265509087, ‖∇f‖ = 7.8232e-11
└ @ OptimKit /home/ashankar/.julia/packages/OptimKit/xpmbV/src/lbfgs.jl:138
┌ Info: UniformCMPS ground state: converged after 329 iterations: e = -2.761265509087, ‖∇e‖ = 7.8232e-11
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:127


D = 8 | InfiniteCMPS{Constant{Matrix{Float64}}, 1}
 58.389162 seconds (28.80 M allocations: 2.564 GiB, 0.36% gc time, 52718006 lock conflicts, 0.38% compilation time)
---------------
 77.869650 seconds (101.93 M allocations: 6.255 GiB, 0.92% gc time, 57294989 lock conflicts, 189.89% compilation time: <1% of which was recompilation)


┌ Info: LBFGS: converged after 347 iterations: f = -2.761265509087, ‖∇f‖ = 8.9374e-11
└ @ OptimKit /home/ashankar/.julia/packages/OptimKit/xpmbV/src/lbfgs.jl:138
┌ Info: UniformCMPS ground state: converged after 348 iterations: e = -2.761265509087, ‖∇e‖ = 8.9374e-11
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:127


D = 8 | InfiniteCMPS{Constant{Matrix{Float64}}, 1}
 61.466364 seconds (30.90 M allocations: 2.737 GiB, 0.38% gc time, 55877832 lock conflicts, 2.01% compilation time)
---------------
 78.056875 seconds (102.04 M allocations: 6.264 GiB, 0.93% gc time, 57401609 lock conflicts, 189.42% compilation time: <1% of which was recompilation)


┌ Info: LBFGS: converged after 339 iterations: f = -2.761265509087, ‖∇f‖ = 1.7491e-11
└ @ OptimKit /home/ashankar/.julia/packages/OptimKit/xpmbV/src/lbfgs.jl:138
┌ Info: UniformCMPS ground state: converged after 340 iterations: e = -2.761265509087, ‖∇e‖ = 1.7491e-11
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:127
┌ Info: LBFGS: converged after 328 iterations: f = -2.761265509087, ‖∇f‖ = 5.0650e-11
└ @ OptimKit /home/ashankar/.julia/packages/OptimKit/xpmbV/src/lbfgs.jl:138
┌ Info: UniformCMPS ground state: converged after 329 iterations: e = -2.761265509087, ‖∇e‖ = 5.0650e-11
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:127


D = 8 | InfiniteCMPS{Constant{Matrix{Float64}}, 1}
 62.245232 seconds (34.57 M allocations: 2.927 GiB, 0.41% gc time, 56494865 lock conflicts, 4.59% compilation time)
---------------
 78.288936 seconds (102.21 M allocations: 6.279 GiB, 0.92% gc time, 57523752 lock conflicts, 188.87% compilation time: <1% of which was recompilation)
D = 8 | InfiniteCMPS{Constant{Matrix{Float64}}, 1}
 62.626078 seconds (35.50 M allocations: 2.973 GiB, 0.41% gc time, 56760020 lock conflicts, 4.57% compilation time)
---------------
 77.617667 seconds (97.76 M allocations: 6.058 GiB, 0.89% gc time, 57588099 lock conflicts, 186.12% compilation time: <1% of which was recompilation)


┌ Info: LBFGS: converged after 338 iterations: f = -2.761265509087, ‖∇f‖ = 3.9393e-11
└ @ OptimKit /home/ashankar/.julia/packages/OptimKit/xpmbV/src/lbfgs.jl:138
┌ Info: UniformCMPS ground state: converged after 339 iterations: e = -2.761265509087, ‖∇e‖ = 3.9393e-11
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:127


D = 8 | InfiniteCMPS{Constant{Matrix{Float64}}, 1}
 60.497193 seconds (30.16 M allocations: 2.682 GiB, 0.37% gc time, 54540364 lock conflicts, 0.36% compilation time)
---------------
 77.702992 seconds (97.83 M allocations: 6.064 GiB, 0.89% gc time, 57594136 lock conflicts, 189.21% compilation time: <1% of which was recompilation)


┌ Info: LBFGS: converged after 349 iterations: f = -2.761265509087, ‖∇f‖ = 1.7491e-11
└ @ OptimKit /home/ashankar/.julia/packages/OptimKit/xpmbV/src/lbfgs.jl:138
┌ Info: UniformCMPS ground state: converged after 350 iterations: e = -2.761265509087, ‖∇e‖ = 1.7491e-11
└ @ CMPSKit /home/ashankar/Documents/PhDstuff/code/TensorNetworks/CMPSKit.jl/src/infinitecmps/groundstate.jl:127


In [4]:
energies

10-element Vector{ComplexF64}:
   -2.76126550908701 + 0.0im
   -2.76126550908695 + 0.0im
 -2.7347478175232447 + 0.0im
 -2.7612655090869214 + 0.0im
  -2.761265509087229 + 0.0im
   -2.76126550908709 + 0.0im
  -2.734747817523189 + 0.0im
 -2.7612655090869462 + 0.0im
 -2.7612655090870346 + 0.0im
  -2.761265509086856 + 0.0im

In [62]:
function leftcanonical(state)
    #leftgauge!(state)
    r = rightenv(state)[1][]
    D, U = eigen(r)
    Q = U \ state.Q[] * U
    R = U \ state.Rs[1][] * U
    return Q, R
end

leftcanonical (generic function with 1 method)

In [63]:
leftcanonical(states[9])[1]

8×8 Matrix{Float64}:
 -1.88146    -0.0316391  -0.993964  -0.054044  …  -0.00788796   0.00054808
  0.0560784  -1.55406    -0.116774   0.491584     -0.0378042    0.00799511
  3.54107    -0.234713   -1.90834   -0.361719     -0.0324084    0.0085166
 -0.490428   -2.51682     0.921371  -1.521         0.14651     -0.0521791
 -0.118624    0.43296    -3.00633   -0.223213      0.0127782   -0.0383652
  1.02651    -1.89264     0.121666  -1.884     …  -0.850228     0.0714416
 -0.727298    1.96659     0.838767   1.48863      -0.791363     0.625847
 -0.125773    1.03513     0.548589   1.31951      -1.55763     -0.359526

In [65]:
leftcanonical(states[1])[1]

8×8 Matrix{Float64}:
 -1.88146     0.0316391   0.993964  -0.054044  …   0.00788796   0.00054808
 -0.0560784  -1.55406    -0.116774  -0.491584     -0.0378042   -0.00799511
 -3.54107    -0.234713   -1.90834    0.361719     -0.0324084   -0.0085166
 -0.490428    2.51682    -0.921371  -1.521        -0.14651     -0.0521791
 -0.118624   -0.43296     3.00633   -0.223213     -0.0127782   -0.0383652
 -1.02651    -1.89264     0.121666   1.884     …  -0.850228    -0.0714416
  0.727298    1.96659     0.838767  -1.48863      -0.791363    -0.625847
 -0.125773   -1.03513    -0.548589   1.31951       1.55763     -0.359526

In [41]:
norm(abs.(leftcanonical(states[3])[1]) .- abs.(leftcanonical(states[1])[1]))

5.348342358564704

In [41]:
trivial_spectrum

10-element Vector{ComplexF64}:
   -0.3238896018656483 + 2.64897077764229e-12im
  -0.11752402116367554 + 3.2710298864596935e-12im
   -0.3334001175085182 + 4.84334350935663e-12im
    0.1910125906319209 - 1.257957917928383e-12im
  -0.07414703651037943 + 3.11231723257596e-12im
 -0.009878452386003312 - 7.989874617725213e-13im
   -0.8222363851899726 - 1.7027931593128013e-12im
   -0.3700353253500449 + 1.892491532409018e-12im
   -0.3977809295462766 + 1.2239960900829292e-12im
   -0.5914233818764258 - 1.4545123990191784e-11im

In [85]:
trivial_spectrum = zeros(ComplexF64, Niter);
HLL = Hsingle_ll(c, μ)

for idx in 1:Niter
    stateLL = states[idx]
    space = InfiniteCMPSExcitationSpace(0, stateLL, stateLL)
    Heff = excitation_matrix(excitation_operator(HLL, space), size(stateLL.Q[], 1))
    vals, vecs = eigsolve(Heff, rand(size(Heff, 2)), 5, :SR, maxiter=200)
    trivial_spectrum[idx] = vals[1]
end

┌ Warning: GMRES linsolve stopped without converging after 100 iterations:
│ * norm of residual = 3.12e-12
│ * number of operations = 2902
└ @ KrylovKit /home/ashankar/.julia/packages/KrylovKit/jC5gU/src/linsolve/gmres.jl:123
┌ Warning: GMRES linsolve stopped without converging after 100 iterations:
│ * norm of residual = 7.57e-12
│ * number of operations = 2902
└ @ KrylovKit /home/ashankar/.julia/packages/KrylovKit/jC5gU/src/linsolve/gmres.jl:123
┌ Warning: GMRES linsolve stopped without converging after 100 iterations:
│ * norm of residual = 1.11e-11
│ * number of operations = 2902
└ @ KrylovKit /home/ashankar/.julia/packages/KrylovKit/jC5gU/src/linsolve/gmres.jl:123
┌ Warning: GMRES linsolve stopped without converging after 100 iterations:
│ * norm of residual = 1.11e-11
│ * number of operations = 2902
└ @ KrylovKit /home/ashankar/.julia/packages/KrylovKit/jC5gU/src/linsolve/gmres.jl:123
┌ Warning: GMRES linsolve stopped without converging after 100 iterations:
│ * norm of residual 

In [83]:
energies

10-element Vector{ComplexF64}:
   -2.76126550908701 + 0.0im
   -2.76126550908695 + 0.0im
 -2.7347478175232447 + 0.0im
 -2.7612655090869214 + 0.0im
  -2.761265509087229 + 0.0im
   -2.76126550908709 + 0.0im
  -2.734747817523189 + 0.0im
 -2.7612655090869462 + 0.0im
 -2.7612655090870346 + 0.0im
  -2.761265509086856 + 0.0im

In [82]:
trivial_spectrum

10-element Vector{ComplexF64}:
 -2.1056698109525844 - 1.2668327964525158e-14im
  -2.105669810952856 + 5.822745617936536e-15im
  -1.909666817026072 + 7.862092053778635e-16im
  -2.105669810949975 - 6.504804814211831e-15im
 -2.1056698109520395 + 8.382467530850279e-16im
 -2.1056698109538265 + 5.806266272031457e-15im
 -1.9096668170276108 + 2.893130232282888e-16im
  -2.105669810953319 - 1.668870131868913e-14im
 -2.1056698109531644 - 5.691291730619698e-15im
 -2.1056698109528544 + 1.3217279985875026e-14im